from __future__ import annotations

from datetime import datetime
from typing import Optional

from sqlalchemy import DateTime, ForeignKey, Integer, String
from sqlalchemy.orm import Mapped, mapped_column

from cosmo.models.base import Base, TimestampMixin


class MerchantRule(Base, TimestampMixin):
    """Per-user pattern → category rule.

    Patterns are matched in priority order: exact > contains > fuzzy > regex.
    ``hit_count`` tracks how often the rule fires; ``last_used_at`` lets us
    surface stale rules. ``source`` distinguishes user-created rules from
    those auto-generated by the categorizer.
    """

    __tablename__ = "merchant_rules"

    id: Mapped[int] = mapped_column(primary_key=True)
    user_id: Mapped[int] = mapped_column(
        ForeignKey("users_v2.id", ondelete="CASCADE"), index=True, nullable=False
    )
    pattern: Mapped[str] = mapped_column(String(256), nullable=False)
    match_type: Mapped[str] = mapped_column(String(16), default="exact", nullable=False)
    # 'exact' | 'contains' | 'fuzzy' | 'regex'
    category_id: Mapped[int] = mapped_column(
        ForeignKey("categories.id", ondelete="CASCADE"), nullable=False
    )
    hit_count: Mapped[int] = mapped_column(Integer, default=0, nullable=False)
    last_used_at: Mapped[Optional[datetime]] = mapped_column(
        DateTime(timezone=True), nullable=True
    )
    source: Mapped[str] = mapped_column(String(8), default="user", nullable=False)
    # 'user' | 'auto'
